import type { EmailTheme } from '@/components/email/email-theme';

// Derived from themes/autono.css by the create-theme skill. Re-run the script
// after changing the CSS rather than editing colors here by hand.
export const autonoTheme: EmailTheme = {
  borderRadius: '6px',
  borderRadiusLg: '12px',
  button: {
    primary: {
      backgroundColor: '#c63a21',
      borderRadius: '6px',
      color: '#faf7f0',
      fontSize: '14px',
      fontWeight: '500',
      paddingX: '24px',
      paddingY: '12px',
    },
    secondary: {
      backgroundColor: 'transparent',
      border: '1px solid #e4e1da',
      borderRadius: '6px',
      color: '#1a1917',
      fontSize: '14px',
      fontWeight: '500',
      paddingX: '24px',
      paddingY: '12px',
    },
  },
  colorBackground: '#faf7f0',
  colorBackgroundMuted: '#f1ede4',
  colorBackgroundSubtle: '#ece7dc',
  colorBorder: '#e4e1da',
  colorBorderSubtle: '#e4e1da',
  colorDanger: '#c63a21',
  colorPrimary: '#c63a21',
  colorPrimaryForeground: '#faf7f0',
  colorPrimaryHover: '#aa1a00',
  colorSuccess: '#10b981',
  colorText: '#1a1917',
  colorTextMuted: '#6b675f',
  colorTextSubtle: '#949088',
  colorWarning: '#f59e0b',
  containerWidth: '600px',
  fontFamily: '"Inter", ui-sans-serif, system-ui, sans-serif',
  fontFamilyMono: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
  fontSizeBase: '14px',
  fontSizeHeading: '28px',
  fontSizeLg: '16px',
  fontSizeSm: '12px',
  fontSizeXl: '20px',
  fontWeightBold: '600',
  fontWeightMedium: '500',
  fontWeightNormal: '400',
  lineHeightBase: '1.6',
  spacingBase: '24px',
  spacingLg: '32px',
  spacingXl: '48px',
};
